### ISSUE TITLE
ValueError: Must have equal len keys and value when setting with an ndarray

### ISSUE THREAD

**Issue by sajidurehman** [zhongliliu/elastool#8] opened 2024-06-06 09:29 UTC
Hi dear developer, 
I am a big fan of elastool. Now I tried the updated version v3.69 for 2D material but I am facing an error. Please find elastool.in and error file. 
Looking forward to hearing from you.
Best regards
Sajid

[Files.zip](https://github.com/user-attachments/files/15612970/Files.zip)

**Comment by gmp007** [comment] 2024-06-06 11:02
Thanks, Sajidurehman for bringing this to my attention. Can you send the
complete zipped folder to enable proper debugging since this error seems
like an isolated case?

**Comment by sajidurehman** [comment] 2024-06-06 11:32
Thank you for your prompt reply. Please find the attached 
[elastool.zip](https://github.com/user-attachments/files/15614500/elastool.zip)

**Comment by gmp007** [comment] 2024-06-06 16:29
Can you confirm that this has been taken care of after you updated your libraries?

**Comment by gmp007** [comment] 2024-06-06 16:35
I sent this more than 4 hours ago, but just realized it didn't go cos of the size restriction. I deleted some files in OPT that won't affect the postprocessing. 
Okay. I cannot reproduce your error. See attached the zipped folder with the results and the screen output as screenout.out. See what I suggest you do. You might be using old version of matminer. Just copy the command below and run it in the terminal to upgrade your libraries to the latest one. 
pip install --upgrade numpy scipy matplotlib pandas seaborn pymatgen kaleido plotly spglib ase pyvista selenium catboost matminer scikit-learn tensorflow keras bayesian-optimization periodictable


Please let me know if this resolves the issue. If not, I can update the code with explicit requirements to use the latest version of python libraries in the setup.
[elastool.zip](https://github.com/user-attachments/files/15657168/elastool.zip)

**Comment by sajidurehman** [comment] 2024-06-07 04:33
Thank you for reply. As per your suggestion I updated all the mentioned libraries (see below) but still getting same error!

Installing collected packages: sortedcontainers, namex, libclang, kaleido, flatbuffers, wrapt, typing_extensions, threadpoolctl, termcolor, tensorflow-io-gcs-filesystem, tensorboard-data-server, sniffio, scooby, requests, pysocks, pygments, protobuf, plotly, platformdirs, numpy, monty, mdurl, MarkupSafe, markdown, h11, grpcio, graphviz, google-pasta, gast, dnspython, colorama, attrs, astunparse, absl-py, wsproto, werkzeug, spglib, scipy, pymongo, pooch, periodictable, pandas, outcome, optree, opt-einsum, ml-dtypes, markdown-it-py, trio, tensorboard, scikit-learn, rich, matplotlib, vtk, trio-websocket, seaborn, pymatgen, keras, catboost, bayesian-optimization, ase, tensorflow, selenium, pyvista, matminer
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: plotly
    Found existing installation: plotly 5.18.0
    Uninstalling plotly-5.18.0:
      Successfully uninstalled plotly-5.18.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.3
    Uninstalling numpy-1.23.3:
      Successfully uninstalled numpy-1.23.3
  Attempting uninstall: monty
    Found existing installation: monty 2023.9.25
    Uninstalling monty-2023.9.25:
      Successfully uninstalled monty-2023.9.25
  Attempting uninstall: spglib
    Found existing installation: spglib 2.1.0
    Uninstalling spglib-2.1.0:
      Successfully uninstalled spglib-2.1.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.3
    Uninstalling scipy-1.11.3:
      Successfully uninstalled scipy-1.11.3
  Attempting uninstall: pandas
    Found existing installation: pandas 2.1.2
    Uninstalling pandas-2.1.2:
      Successfully uninstalled pandas-2.1.2
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.8.0
    Uninstalling matplotlib-3.8.0:
      Successfully uninstalled matplotlib-3.8.0
  Attempting uninstall: pymatgen
    Found existing installation: pymatgen 2023.10.11
    Uninstalling pymatgen-2023.10.11:
      Successfully uninstalled pymatgen-2023.10.11
  Attempting uninstall: ase
    Found existing installation: ase 3.22.1
    Uninstalling ase-3.22.1:
      Successfully uninstalled ase-3.22.1
Successfully installed MarkupSafe-2.1.5 absl-py-2.1.0 ase-3.23.0 astunparse-1.6.3 attrs-23.2.0 bayesian-optimization-1.4.3 catboost-1.2.5 colorama-0.4.6 dnspython-2.6.1 flatbuffers-24.3.25 gast-0.5.4 google-pasta-0.2.0 graphviz-0.20.3 grpcio-1.64.1 h11-0.14.0 kaleido-0.2.1 keras-3.3.3 libclang-18.1.1 markdown-3.6 markdown-it-py-3.0.0 matminer-0.9.2 matplotlib-3.9.0 mdurl-0.1.2 ml-dtypes-0.3.2 monty-2024.5.24 namex-0.0.8 numpy-1.26.4 opt-einsum-3.3.0 optree-0.11.0 outcome-1.3.0.post0 pandas-2.2.2 periodictable-1.7.0 platformdirs-4.2.2 plotly-5.22.0 pooch-1.8.2 protobuf-4.25.3 pygments-2.18.0 pymatgen-2024.6.4 pymongo-4.7.3 pysocks-1.7.1 pyvista-0.43.9 requests-2.32.3 rich-13.7.1 scikit-learn-1.5.0 scipy-1.13.1 scooby-0.10.0 seaborn-0.13.2 selenium-4.21.0 sniffio-1.3.1 sortedcontainers-2.4.0 spglib-2.4.0 tensorboard-2.16.2 tensorboard-data-server-0.7.2 tensorflow-2.16.1 tensorflow-io-gcs-filesystem-0.37.0 termcolor-2.4.0 threadpoolctl-3.5.0 trio-0.25.1 trio-websocket-0.11.1 typing_extensions-4.12.1 vtk-9.3.0 werkzeug-3.0.3 wrapt-1.16.0 wsproto-1.2.0

**Comment by gmp007** [comment] 2024-06-07 05:19
As I am unable to reproduce this error, it is difficult to debug. As you can see, the previous code I sent to you ran successfully. Another option is to create a fresh environment for and install it.

**Comment by sajidurehman** [comment] 2024-06-07 06:07
Thank you for your assistance in resolving my issue. elastool is now functioning properly.

I have one additional question. Are there any plans to include Grüneisen parameter calculation functionality in future updates?

**Comment by gmp007** [comment] 2024-06-07 15:43
Great, thanks to hear that the error is taken care of. Grüneisen parameter is already implemented in this version. I will go ahead and close this now as resolved. Let me know if you have any additional question.

**Closed as completed by gmp007** 2024-06-07 15:43 UTC
